import {
  ChevronLeft,
  ChevronRight,
  Moon,
  Sun,
  Laptop,
  ArrowRightIcon,
  ShieldAlert,
  Users2Icon,
  PersonStandingIcon,
  ActivityIcon,
  LocateOffIcon,
  CheckCircle2Icon,
  ChevronsUpDownIcon,
  Building2Icon,
  CompassIcon,
  BadgeCheckIcon,
  SearchIcon,
  PhoneIcon,
} from 'lucide-react';

export const Icons = {
  ChevronLeft,
  ChevronRight,
  Sun,
  Moon,
  Laptop,
  ArrowRightIcon,
  ShieldAlert,
  Users2Icon,
  PersonStandingIcon,
  ActivityIcon,
  LocateOffIcon,
  CheckCircle2Icon,
  ChevronsUpDownIcon,
  Building2Icon,
  CompassIcon,
  BadgeCheckIcon,
  SearchIcon,
  PhoneIcon,
};

export default Icons;
